server {
    listen 80;

    root /usr/share/nginx/html;
    index index.html;

    location /greengo/ {
        try_files $uri $uri/ /greengo/index.html;
    }

    location /greengo/api/ {
        proxy_pass http://backend:8000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
