services:
  db:
    container_name: routio-db
    restart: unless-stopped
    image: postgis/postgis:16-3.4
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 20
    networks:
      - backend-db

  backend:
    container_name: routio-backend
    restart: unless-stopped
    image: dexter.fit.vutbr.cz/routio/routio-backend
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      TZ: Europe/Bratislava
      PRODUCTION: true
    depends_on:
      db:
        condition: service_healthy
    networks:
      - routioNetwork
      - backend-db

  frontend:
    container_name: routio-frontend
    restart: unless-stopped
    image: dexter.fit.vutbr.cz/routio/routio-frontend
    depends_on:
      - backend
    networks:
      - routioNetwork

  proxy:
    container_name: routio-proxy
    image: nginx:1.19
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend
    networks:
      - routioNetwork
      - network

networks:
  network:
    name: kristyna-dev
    external: true
  routioNetwork:
    name: routioNetwork
  backend-db:

volumes:
  pgdata:
