events {}

http {
    include mime.types;

    upstream be {
        server routio-backend:8000;
    }

    upstream fe {
        server routio-frontend;
    }

    server {
        listen 80;

        include /etc/nginx/mime.types;

        location /routio/api/ {
            proxy_pass http://be/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location /routio {
            proxy_pass http://fe/routio/;
        }
    }
}
