FROM python:3.12-slim
WORKDIR /app

RUN apt-get update && apt-get install -y gcc libexpat1 && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .

RUN pip install -r requirements.txt

COPY src/ .

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
